<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class MenuSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $admin_menus = array(
            array(
                "id" => 1,
                "name" => "Navigation Menu",
                "created_at" => "2025-03-12 12:24:05",
                "updated_at" => "2025-03-12 12:24:06",
            ),
            array(
                "id" => 2,
                "name" => "Footer Menu Two",
                "created_at" => "2025-03-12 09:26:10",
                "updated_at" => "2025-03-12 09:26:31",
            ),
            array(
                "id" => 4,
                "name" => "Footer Menu One",
                "created_at" => "2025-03-12 09:32:55",
                "updated_at" => "2025-03-12 09:32:55",
            ),
            array(
                "id" => 6,
                "name" => "Footer Menu Three",
                "created_at" => "2025-03-12 09:34:01",
                "updated_at" => "2025-03-12 09:34:01",
            ),
            array(
                "id" => 8,
                "name" => "Footer Menu Four",
                "created_at" => "2025-03-12 09:34:38",
                "updated_at" => "2025-03-12 09:34:38",
            ),
        );
        \DB::table('admin_menus')->insert($admin_menus);

        $admin_menu_items = array(
            array(
                "id" => 1,
                "label" => "Home",
                "link" => "/",
                "parent_id" => 0,
                "sort" => 0,
                "class" => NULL,
                "menu_id" => 1,
                "depth" => 0,
                "created_at" => "2025-03-20 08:57:33",
                "updated_at" => "2025-03-20 08:58:28",
            ),
            array(
                "id" => 2,
                "label" => "Companies",
                "link" => "/companies",
                "parent_id" => 0,
                "sort" => 1,
                "class" => NULL,
                "menu_id" => 1,
                "depth" => 0,
                "created_at" => "2025-03-20 08:58:28",
                "updated_at" => "2025-03-20 08:58:35",
            ),
            array(
                "id" => 3,
                "label" => "Candidates",
                "link" => "/candidates",
                "parent_id" => 0,
                "sort" => 2,
                "class" => NULL,
                "menu_id" => 1,
                "depth" => 0,
                "created_at" => "2025-03-20 08:58:35",
                "updated_at" => "2025-03-20 08:58:49",
            ),
            array(
                "id" => 4,
                "label" => "Jobs",
                "link" => "/jobs",
                "parent_id" => 0,
                "sort" => 3,
                "class" => NULL,
                "menu_id" => 1,
                "depth" => 0,
                "created_at" => "2025-03-20 08:58:49",
                "updated_at" => "2025-03-20 08:58:51",
            ),
            array(
                "id" => 5,
                "label" => "Blogs",
                "link" => "/blogs",
                "parent_id" => 0,
                "sort" => 8,
                "class" => NULL,
                "menu_id" => 1,
                "depth" => 0,
                "created_at" => "2025-03-20 08:59:04",
                "updated_at" => "2025-03-20 09:01:09",
            ),
            array(
                "id" => 6,
                "label" => "Pricing",
                "link" => "/pricing",
                "parent_id" => 0,
                "sort" => 4,
                "class" => NULL,
                "menu_id" => 1,
                "depth" => 0,
                "created_at" => "2025-03-20 08:59:23",
                "updated_at" => "2025-03-20 09:01:39",
            ),
            array(
                "id" => 7,
                "label" => "Pages",
                "link" => "#",
                "parent_id" => 0,
                "sort" => 5,
                "class" => NULL,
                "menu_id" => 1,
                "depth" => 0,
                "created_at" => "2025-03-20 09:00:10",
                "updated_at" => "2025-03-20 09:01:09",
            ),
            array(
                "id" => 8,
                "label" => "About US",
                "link" => "/about-us",
                "parent_id" => 7,
                "sort" => 6,
                "class" => NULL,
                "menu_id" => 1,
                "depth" => 1,
                "created_at" => "2025-03-20 09:00:27",
                "updated_at" => "2025-03-20 09:01:09",
            ),
            array(
                "id" => 9,
                "label" => "Contact US",
                "link" => "/contact",
                "parent_id" => 7,
                "sort" => 7,
                "class" => NULL,
                "menu_id" => 1,
                "depth" => 1,
                "created_at" => "2025-03-20 09:00:36",
                "updated_at" => "2025-03-20 09:01:09",
            ),
            array(
                "id" => 10,
                "label" => "Blog",
                "link" => "/blogs",
                "parent_id" => 0,
                "sort" => 0,
                "class" => NULL,
                "menu_id" => 4,
                "depth" => 0,
                "created_at" => "2025-03-20 09:04:37",
                "updated_at" => "2025-03-20 09:04:52",
            ),
            array(
                "id" => 11,
                "label" => "About us",
                "link" => "/about-us",
                "parent_id" => 0,
                "sort" => 2,
                "class" => NULL,
                "menu_id" => 4,
                "depth" => 0,
                "created_at" => "2025-03-20 09:04:52",
                "updated_at" => "2025-03-20 09:04:52",
            ),
            array(
                "id" => 12,
                "label" => "Contact",
                "link" => "/contact",
                "parent_id" => 0,
                "sort" => 0,
                "class" => NULL,
                "menu_id" => 2,
                "depth" => 0,
                "created_at" => "2025-03-20 09:05:44",
                "updated_at" => "2025-03-20 09:05:47",
            ),
            array(
                "id" => 13,
                "label" => "Pricing",
                "link" => "/pricing",
                "parent_id" => 0,
                "sort" => 0,
                "class" => NULL,
                "menu_id" => 6,
                "depth" => 0,
                "created_at" => "2025-03-20 09:06:38",
                "updated_at" => "2025-03-20 09:06:40",
            ),
            array(
                "id" => 14,
                "label" => "Home",
                "link" => "/",
                "parent_id" => 0,
                "sort" => 1,
                "class" => NULL,
                "menu_id" => 8,
                "depth" => 0,
                "created_at" => "2025-03-20 09:06:56",
                "updated_at" => "2025-03-20 09:06:56",
            ),
        );
        \DB::table('admin_menu_items')->insert($admin_menu_items);
    }
}
