<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class RolePermissionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $permissions = array(
            array(
                "id" => 1,
                "name" => "dashboard analytics",
                "guard_name" => "admin",
                "group" => "Dashboard",
                "created_at" => "2025-03-17 07:24:30",
                "updated_at" => "2025-03-17 07:24:30",
            ),
            array(
                "id" => 2,
                "name" => "dashboard pending posts",
                "guard_name" => "admin",
                "group" => "Dashboard",
                "created_at" => "2025-03-17 07:24:50",
                "updated_at" => "2025-03-17 07:24:50",
            ),
            array(
                "id" => 3,
                "name" => "order index",
                "guard_name" => "admin",
                "group" => "Order",
                "created_at" => "2025-03-17 08:32:57",
                "updated_at" => "2025-03-17 08:32:57",
            ),
            array(
                "id" => 4,
                "name" => "job category create",
                "guard_name" => "admin",
                "group" => "Job Category",
                "created_at" => "2025-03-17 08:35:05",
                "updated_at" => "2025-03-17 08:35:05",
            ),
            array(
                "id" => 5,
                "name" => "job category update",
                "guard_name" => "admin",
                "group" => "Job Category",
                "created_at" => "2025-03-17 08:35:32",
                "updated_at" => "2025-03-17 08:35:32",
            ),
            array(
                "id" => 6,
                "name" => "job category delete",
                "guard_name" => "admin",
                "group" => "Job Category",
                "created_at" => "2025-03-17 08:35:48",
                "updated_at" => "2025-03-17 08:35:48",
            ),
            array(
                "id" => 7,
                "name" => "job create",
                "guard_name" => "admin",
                "group" => "Job",
                "created_at" => "2025-03-17 08:40:18",
                "updated_at" => "2025-03-17 08:40:18",
            ),
            array(
                "id" => 8,
                "name" => "job update",
                "guard_name" => "admin",
                "group" => "Job",
                "created_at" => "2025-03-17 08:40:41",
                "updated_at" => "2025-03-17 08:40:41",
            ),
            array(
                "id" => 9,
                "name" => "job delete",
                "guard_name" => "admin",
                "group" => "Job",
                "created_at" => "2025-03-17 08:41:03",
                "updated_at" => "2025-03-17 08:41:03",
            ),
            array(
                "id" => 10,
                "name" => "job role create",
                "guard_name" => "admin",
                "group" => "Job Role",
                "created_at" => "2025-03-17 08:44:07",
                "updated_at" => "2025-03-17 08:44:07",
            ),
            array(
                "id" => 15,
                "name" => "site footer",
                "guard_name" => "admin",
                "group" => "Site Footer",
                "created_at" => "2025-03-17 08:57:13",
                "updated_at" => "2025-03-17 08:57:13",
            ),
            array(
                "id" => 16,
                "name" => "blog create",
                "guard_name" => "admin",
                "group" => "blog",
                "created_at" => "2025-03-17 08:59:25",
                "updated_at" => "2025-03-17 08:59:25",
            ),
            array(
                "id" => 17,
                "name" => "plan create",
                "guard_name" => "admin",
                "group" => "plan",
                "created_at" => "2025-03-17 09:00:25",
                "updated_at" => "2025-03-17 09:00:25",
            ),
            array(
                "id" => 18,
                "name" => "news letter",
                "guard_name" => "admin",
                "group" => "News Letter",
                "created_at" => "2025-03-17 09:02:03",
                "updated_at" => "2025-03-17 09:02:03",
            ),
            array(
                "id" => 19,
                "name" => "menu builder",
                "guard_name" => "admin",
                "group" => "Menu Builder",
                "created_at" => "2025-03-17 09:03:43",
                "updated_at" => "2025-03-17 09:03:43",
            ),
            array(
                "id" => 21,
                "name" => "payment settings",
                "guard_name" => "admin",
                "group" => "Payment Settings",
                "created_at" => "2025-03-17 09:09:38",
                "updated_at" => "2025-03-17 09:09:38",
            ),
            array(
                "id" => 22,
                "name" => "site settings",
                "guard_name" => "admin",
                "group" => "Site Settings",
                "created_at" => "2025-03-17 09:09:51",
                "updated_at" => "2025-03-17 09:09:51",
            ),
            array(
                "id" => 23,
                "name" => "database clear",
                "guard_name" => "admin",
                "group" => "Database Clear",
                "created_at" => "2025-03-17 09:10:08",
                "updated_at" => "2025-03-17 09:10:08",
            ),
            array(
                "id" => 28,
                "name" => "job role update",
                "guard_name" => "admin",
                "group" => "Job Role",
                "created_at" => "2025-03-21 10:02:38",
                "updated_at" => "2025-03-21 10:02:38",
            ),
            array(
                "id" => 29,
                "name" => "job role delete",
                "guard_name" => "admin",
                "group" => "Job Role",
                "created_at" => "2025-03-21 10:02:48",
                "updated_at" => "2025-03-21 10:02:48",
            ),
            array(
                "id" => 30,
                "name" => "industry create",
                "guard_name" => "admin",
                "group" => "industry",
                "created_at" => "2025-03-21 10:11:57",
                "updated_at" => "2025-03-21 10:11:57",
            ),
            array(
                "id" => 31,
                "name" => "industry update",
                "guard_name" => "admin",
                "group" => "industry",
                "created_at" => "2025-03-21 10:12:08",
                "updated_at" => "2025-03-21 10:12:08",
            ),
            array(
                "id" => 32,
                "name" => "industry delete",
                "guard_name" => "admin",
                "group" => "industry",
                "created_at" => "2025-03-21 10:12:17",
                "updated_at" => "2025-03-21 10:12:17",
            ),
            array(
                "id" => 33,
                "name" => "organization create",
                "guard_name" => "admin",
                "group" => "organization",
                "created_at" => "2025-03-21 10:12:34",
                "updated_at" => "2025-03-21 10:12:34",
            ),
            array(
                "id" => 34,
                "name" => "organization update",
                "guard_name" => "admin",
                "group" => "organization",
                "created_at" => "2025-03-21 10:12:45",
                "updated_at" => "2025-03-21 10:12:45",
            ),
            array(
                "id" => 35,
                "name" => "organization delete",
                "guard_name" => "admin",
                "group" => "organization",
                "created_at" => "2025-03-21 10:12:53",
                "updated_at" => "2025-03-21 10:12:53",
            ),
            array(
                "id" => 36,
                "name" => "language create",
                "guard_name" => "admin",
                "group" => "language",
                "created_at" => "2025-03-21 10:13:14",
                "updated_at" => "2025-03-21 10:13:14",
            ),
            array(
                "id" => 37,
                "name" => "language update",
                "guard_name" => "admin",
                "group" => "language",
                "created_at" => "2025-03-21 10:13:22",
                "updated_at" => "2025-03-21 10:13:22",
            ),
            array(
                "id" => 38,
                "name" => "language delete",
                "guard_name" => "admin",
                "group" => "language",
                "created_at" => "2025-03-21 10:13:32",
                "updated_at" => "2025-03-21 10:13:32",
            ),
            array(
                "id" => 39,
                "name" => "profession create",
                "guard_name" => "admin",
                "group" => "profession",
                "created_at" => "2025-03-21 10:14:00",
                "updated_at" => "2025-03-21 10:14:00",
            ),
            array(
                "id" => 40,
                "name" => "profession update",
                "guard_name" => "admin",
                "group" => "profession",
                "created_at" => "2025-03-21 10:14:10",
                "updated_at" => "2025-03-21 10:14:10",
            ),
            array(
                "id" => 41,
                "name" => "profession delete",
                "guard_name" => "admin",
                "group" => "profession",
                "created_at" => "2025-03-21 10:14:18",
                "updated_at" => "2025-03-21 10:14:18",
            ),
            array(
                "id" => 42,
                "name" => "skill create",
                "guard_name" => "admin",
                "group" => "skill",
                "created_at" => "2025-03-21 10:14:33",
                "updated_at" => "2025-03-21 10:14:33",
            ),
            array(
                "id" => 43,
                "name" => "skill update",
                "guard_name" => "admin",
                "group" => "skill",
                "created_at" => "2025-03-21 10:14:43",
                "updated_at" => "2025-03-21 10:14:43",
            ),
            array(
                "id" => 44,
                "name" => "skill delete",
                "guard_name" => "admin",
                "group" => "skill",
                "created_at" => "2025-03-21 10:14:51",
                "updated_at" => "2025-03-21 10:14:51",
            ),
            array(
                "id" => 45,
                "name" => "education create",
                "guard_name" => "admin",
                "group" => "education",
                "created_at" => "2025-03-21 10:15:05",
                "updated_at" => "2025-03-21 10:15:05",
            ),
            array(
                "id" => 46,
                "name" => "education update",
                "guard_name" => "admin",
                "group" => "education",
                "created_at" => "2025-03-21 10:15:16",
                "updated_at" => "2025-03-21 10:15:16",
            ),
            array(
                "id" => 47,
                "name" => "education delete",
                "guard_name" => "admin",
                "group" => "education",
                "created_at" => "2025-03-21 10:15:25",
                "updated_at" => "2025-03-21 10:15:25",
            ),
            array(
                "id" => 48,
                "name" => "jobtype create",
                "guard_name" => "admin",
                "group" => "jobtype",
                "created_at" => "2025-03-21 10:15:41",
                "updated_at" => "2025-03-21 10:15:41",
            ),
            array(
                "id" => 49,
                "name" => "jobtype update",
                "guard_name" => "admin",
                "group" => "jobtype",
                "created_at" => "2025-03-21 10:15:49",
                "updated_at" => "2025-03-21 10:15:49",
            ),
            array(
                "id" => 50,
                "name" => "jobtype delete",
                "guard_name" => "admin",
                "group" => "jobtype",
                "created_at" => "2025-03-21 10:15:58",
                "updated_at" => "2025-03-21 10:15:58",
            ),
            array(
                "id" => 51,
                "name" => "salarytype create",
                "guard_name" => "admin",
                "group" => "salarytype",
                "created_at" => "2025-03-21 10:16:15",
                "updated_at" => "2025-03-21 10:16:15",
            ),
            array(
                "id" => 52,
                "name" => "salarytype update",
                "guard_name" => "admin",
                "group" => "salarytype",
                "created_at" => "2025-03-21 10:16:23",
                "updated_at" => "2025-03-21 10:16:23",
            ),
            array(
                "id" => 53,
                "name" => "salarytype delete",
                "guard_name" => "admin",
                "group" => "salarytype",
                "created_at" => "2025-03-21 10:16:34",
                "updated_at" => "2025-03-21 10:16:34",
            ),
            array(
                "id" => 54,
                "name" => "tag create",
                "guard_name" => "admin",
                "group" => "tag",
                "created_at" => "2025-03-21 10:16:48",
                "updated_at" => "2025-03-21 10:16:48",
            ),
            array(
                "id" => 55,
                "name" => "tag update",
                "guard_name" => "admin",
                "group" => "tag",
                "created_at" => "2025-03-21 10:16:57",
                "updated_at" => "2025-03-21 10:16:57",
            ),
            array(
                "id" => 56,
                "name" => "tag delete",
                "guard_name" => "admin",
                "group" => "tag",
                "created_at" => "2025-03-21 10:17:05",
                "updated_at" => "2025-03-21 10:17:05",
            ),
            array(
                "id" => 57,
                "name" => "experience create",
                "guard_name" => "admin",
                "group" => "experience",
                "created_at" => "2025-03-21 10:17:20",
                "updated_at" => "2025-03-21 10:17:20",
            ),
            array(
                "id" => 58,
                "name" => "experience update",
                "guard_name" => "admin",
                "group" => "experience",
                "created_at" => "2025-03-21 10:17:28",
                "updated_at" => "2025-03-21 10:17:28",
            ),
            array(
                "id" => 59,
                "name" => "experience delete",
                "guard_name" => "admin",
                "group" => "experience",
                "created_at" => "2025-03-21 10:17:35",
                "updated_at" => "2025-03-21 10:17:35",
            ),
            array(
                "id" => 60,
                "name" => "country create",
                "guard_name" => "admin",
                "group" => "country",
                "created_at" => "2025-03-21 12:07:16",
                "updated_at" => "2025-03-21 12:07:16",
            ),
            array(
                "id" => 61,
                "name" => "country update",
                "guard_name" => "admin",
                "group" => "country",
                "created_at" => "2025-03-21 12:07:25",
                "updated_at" => "2025-03-21 12:07:25",
            ),
            array(
                "id" => 62,
                "name" => "country delete",
                "guard_name" => "admin",
                "group" => "country",
                "created_at" => "2025-03-21 12:07:33",
                "updated_at" => "2025-03-21 12:07:33",
            ),
            array(
                "id" => 63,
                "name" => "state create",
                "guard_name" => "admin",
                "group" => "state",
                "created_at" => "2025-03-21 12:07:46",
                "updated_at" => "2025-03-21 12:07:46",
            ),
            array(
                "id" => 64,
                "name" => "state update",
                "guard_name" => "admin",
                "group" => "state",
                "created_at" => "2025-03-21 12:07:53",
                "updated_at" => "2025-03-21 12:07:53",
            ),
            array(
                "id" => 65,
                "name" => "state delete",
                "guard_name" => "admin",
                "group" => "state",
                "created_at" => "2025-03-21 12:08:02",
                "updated_at" => "2025-03-21 12:08:02",
            ),
            array(
                "id" => 66,
                "name" => "city create",
                "guard_name" => "admin",
                "group" => "city",
                "created_at" => "2025-03-21 12:08:13",
                "updated_at" => "2025-03-21 12:08:13",
            ),
            array(
                "id" => 67,
                "name" => "city update",
                "guard_name" => "admin",
                "group" => "city",
                "created_at" => "2025-03-21 12:08:27",
                "updated_at" => "2025-03-21 12:08:27",
            ),
            array(
                "id" => 68,
                "name" => "city delete",
                "guard_name" => "admin",
                "group" => "city",
                "created_at" => "2025-03-21 12:08:37",
                "updated_at" => "2025-03-21 12:08:37",
            ),
            array(
                "id" => 69,
                "name" => "hero",
                "guard_name" => "admin",
                "group" => "hero",
                "created_at" => "2025-03-21 12:17:17",
                "updated_at" => "2025-03-21 12:17:17",
            ),
            array(
                "id" => 70,
                "name" => "whychooseus",
                "guard_name" => "admin",
                "group" => "whychooseus",
                "created_at" => "2025-03-21 12:17:34",
                "updated_at" => "2025-03-21 12:17:34",
            ),
            array(
                "id" => 71,
                "name" => "learnmore",
                "guard_name" => "admin",
                "group" => "learnmore",
                "created_at" => "2025-03-21 12:17:56",
                "updated_at" => "2025-03-21 12:17:56",
            ),
            array(
                "id" => 72,
                "name" => "counter",
                "guard_name" => "admin",
                "group" => "counter",
                "created_at" => "2025-03-21 12:18:11",
                "updated_at" => "2025-03-21 12:18:11",
            ),
            array(
                "id" => 73,
                "name" => "job location create",
                "guard_name" => "admin",
                "group" => "job location",
                "created_at" => "2025-03-21 12:18:44",
                "updated_at" => "2025-03-21 12:18:44",
            ),
            array(
                "id" => 74,
                "name" => "job location update",
                "guard_name" => "admin",
                "group" => "job location",
                "created_at" => "2025-03-21 12:18:53",
                "updated_at" => "2025-03-21 12:18:53",
            ),
            array(
                "id" => 75,
                "name" => "job location delete",
                "guard_name" => "admin",
                "group" => "job location",
                "created_at" => "2025-03-21 12:19:02",
                "updated_at" => "2025-03-21 12:19:02",
            ),
            array(
                "id" => 76,
                "name" => "review create",
                "guard_name" => "admin",
                "group" => "review",
                "created_at" => "2025-03-21 12:19:26",
                "updated_at" => "2025-03-21 12:19:26",
            ),
            array(
                "id" => 77,
                "name" => "review update",
                "guard_name" => "admin",
                "group" => "review",
                "created_at" => "2025-03-21 12:19:32",
                "updated_at" => "2025-03-21 12:19:32",
            ),
            array(
                "id" => 78,
                "name" => "review delete",
                "guard_name" => "admin",
                "group" => "review",
                "created_at" => "2025-03-21 12:19:39",
                "updated_at" => "2025-03-21 12:19:39",
            ),
            array(
                "id" => 79,
                "name" => "aboutus",
                "guard_name" => "admin",
                "group" => "aboutus",
                "created_at" => "2025-03-21 12:30:12",
                "updated_at" => "2025-03-21 12:30:12",
            ),
            array(
                "id" => 80,
                "name" => "pagebuilder create",
                "guard_name" => "admin",
                "group" => "pagebuilder",
                "created_at" => "2025-03-21 12:30:42",
                "updated_at" => "2025-03-21 12:30:42",
            ),
            array(
                "id" => 81,
                "name" => "pagebuilder update",
                "guard_name" => "admin",
                "group" => "pagebuilder",
                "created_at" => "2025-03-21 12:30:48",
                "updated_at" => "2025-03-21 12:30:48",
            ),
            array(
                "id" => 82,
                "name" => "pagebuilder delete",
                "guard_name" => "admin",
                "group" => "pagebuilder",
                "created_at" => "2025-03-21 12:30:55",
                "updated_at" => "2025-03-21 12:30:55",
            ),
            array(
                "id" => 83,
                "name" => "blog update",
                "guard_name" => "admin",
                "group" => "blog",
                "created_at" => "2025-03-21 12:39:30",
                "updated_at" => "2025-03-21 12:39:30",
            ),
            array(
                "id" => 84,
                "name" => "blog delete",
                "guard_name" => "admin",
                "group" => "blog",
                "created_at" => "2025-03-21 12:39:45",
                "updated_at" => "2025-03-21 12:39:45",
            ),
            array(
                "id" => 85,
                "name" => "plan update",
                "guard_name" => "admin",
                "group" => "plan",
                "created_at" => "2025-03-21 12:41:27",
                "updated_at" => "2025-03-21 12:41:27",
            ),
            array(
                "id" => 86,
                "name" => "plan delete",
                "guard_name" => "admin",
                "group" => "plan",
                "created_at" => "2025-03-21 12:41:33",
                "updated_at" => "2025-03-21 12:41:33",
            ),
            array(
                "id" => 87,
                "name" => "roleuser create",
                "guard_name" => "admin",
                "group" => "roleuser",
                "created_at" => "2025-03-21 12:56:55",
                "updated_at" => "2025-03-21 12:56:55",
            ),
            array(
                "id" => 88,
                "name" => "roleuser update",
                "guard_name" => "admin",
                "group" => "roleuser",
                "created_at" => "2025-03-21 13:00:17",
                "updated_at" => "2025-03-21 13:00:17",
            ),
            array(
                "id" => 89,
                "name" => "roleuser delete",
                "guard_name" => "admin",
                "group" => "roleuser",
                "created_at" => "2025-03-21 13:00:24",
                "updated_at" => "2025-03-21 13:00:24",
            ),
            array(
                "id" => 90,
                "name" => "role create",
                "guard_name" => "admin",
                "group" => "role",
                "created_at" => "2025-03-21 13:00:31",
                "updated_at" => "2025-03-21 13:00:31",
            ),
            array(
                "id" => 91,
                "name" => "role update",
                "guard_name" => "admin",
                "group" => "role",
                "created_at" => "2025-03-21 13:00:39",
                "updated_at" => "2025-03-21 13:00:39",
            ),
            array(
                "id" => 92,
                "name" => "role delete",
                "guard_name" => "admin",
                "group" => "role",
                "created_at" => "2025-03-21 13:00:46",
                "updated_at" => "2025-03-21 13:00:46",
            ),
        );
        \DB::table('permissions')->insert($permissions);

        $roles = array(
            array(
                "id" => 1,
                "name" => "Super Admin",
                "guard_name" => "admin",
                "created_at" => "2025-03-17 11:31:12",
                "updated_at" => "2025-03-17 11:31:12",
            ),
        );
        \DB::table('roles')->insert($roles);

        $role_has_permissions = array(
            array(
                "permission_id" => 1,
                "role_id" => 1,
            ),
            array(
                "permission_id" => 2,
                "role_id" => 1,
            ),
            array(
                "permission_id" => 3,
                "role_id" => 1,
            ),
            array(
                "permission_id" => 4,
                "role_id" => 1,
            ),
            array(
                "permission_id" => 5,
                "role_id" => 1,
            ),
            array(
                "permission_id" => 6,
                "role_id" => 1,
            ),
            array(
                "permission_id" => 7,
                "role_id" => 1,
            ),
            array(
                "permission_id" => 8,
                "role_id" => 1,
            ),
            array(
                "permission_id" => 9,
                "role_id" => 1,
            ),
            array(
                "permission_id" => 10,
                "role_id" => 1,
            ),
            array(
                "permission_id" => 15,
                "role_id" => 1,
            ),
            array(
                "permission_id" => 16,
                "role_id" => 1,
            ),
            array(
                "permission_id" => 17,
                "role_id" => 1,
            ),
            array(
                "permission_id" => 18,
                "role_id" => 1,
            ),
            array(
                "permission_id" => 19,
                "role_id" => 1,
            ),
            array(
                "permission_id" => 21,
                "role_id" => 1,
            ),
            array(
                "permission_id" => 22,
                "role_id" => 1,
            ),
            array(
                "permission_id" => 23,
                "role_id" => 1,
            ),
            array(
                "permission_id" => 28,
                "role_id" => 1,
            ),
            array(
                "permission_id" => 29,
                "role_id" => 1,
            ),
            array(
                "permission_id" => 30,
                "role_id" => 1,
            ),
            array(
                "permission_id" => 31,
                "role_id" => 1,
            ),
            array(
                "permission_id" => 32,
                "role_id" => 1,
            ),
            array(
                "permission_id" => 33,
                "role_id" => 1,
            ),
            array(
                "permission_id" => 34,
                "role_id" => 1,
            ),
            array(
                "permission_id" => 35,
                "role_id" => 1,
            ),
            array(
                "permission_id" => 36,
                "role_id" => 1,
            ),
            array(
                "permission_id" => 37,
                "role_id" => 1,
            ),
            array(
                "permission_id" => 38,
                "role_id" => 1,
            ),
            array(
                "permission_id" => 39,
                "role_id" => 1,
            ),
            array(
                "permission_id" => 40,
                "role_id" => 1,
            ),
            array(
                "permission_id" => 41,
                "role_id" => 1,
            ),
            array(
                "permission_id" => 42,
                "role_id" => 1,
            ),
            array(
                "permission_id" => 43,
                "role_id" => 1,
            ),
            array(
                "permission_id" => 44,
                "role_id" => 1,
            ),
            array(
                "permission_id" => 45,
                "role_id" => 1,
            ),
            array(
                "permission_id" => 46,
                "role_id" => 1,
            ),
            array(
                "permission_id" => 47,
                "role_id" => 1,
            ),
            array(
                "permission_id" => 48,
                "role_id" => 1,
            ),
            array(
                "permission_id" => 49,
                "role_id" => 1,
            ),
            array(
                "permission_id" => 50,
                "role_id" => 1,
            ),
            array(
                "permission_id" => 51,
                "role_id" => 1,
            ),
            array(
                "permission_id" => 52,
                "role_id" => 1,
            ),
            array(
                "permission_id" => 53,
                "role_id" => 1,
            ),
            array(
                "permission_id" => 54,
                "role_id" => 1,
            ),
            array(
                "permission_id" => 55,
                "role_id" => 1,
            ),
            array(
                "permission_id" => 56,
                "role_id" => 1,
            ),
            array(
                "permission_id" => 57,
                "role_id" => 1,
            ),
            array(
                "permission_id" => 58,
                "role_id" => 1,
            ),
            array(
                "permission_id" => 59,
                "role_id" => 1,
            ),
            array(
                "permission_id" => 60,
                "role_id" => 1,
            ),
            array(
                "permission_id" => 61,
                "role_id" => 1,
            ),
            array(
                "permission_id" => 62,
                "role_id" => 1,
            ),
            array(
                "permission_id" => 63,
                "role_id" => 1,
            ),
            array(
                "permission_id" => 64,
                "role_id" => 1,
            ),
            array(
                "permission_id" => 65,
                "role_id" => 1,
            ),
            array(
                "permission_id" => 66,
                "role_id" => 1,
            ),
            array(
                "permission_id" => 67,
                "role_id" => 1,
            ),
            array(
                "permission_id" => 68,
                "role_id" => 1,
            ),
            array(
                "permission_id" => 69,
                "role_id" => 1,
            ),
            array(
                "permission_id" => 70,
                "role_id" => 1,
            ),
            array(
                "permission_id" => 71,
                "role_id" => 1,
            ),
            array(
                "permission_id" => 72,
                "role_id" => 1,
            ),
            array(
                "permission_id" => 73,
                "role_id" => 1,
            ),
            array(
                "permission_id" => 74,
                "role_id" => 1,
            ),
            array(
                "permission_id" => 75,
                "role_id" => 1,
            ),
            array(
                "permission_id" => 76,
                "role_id" => 1,
            ),
            array(
                "permission_id" => 77,
                "role_id" => 1,
            ),
            array(
                "permission_id" => 78,
                "role_id" => 1,
            ),
            array(
                "permission_id" => 79,
                "role_id" => 1,
            ),
            array(
                "permission_id" => 80,
                "role_id" => 1,
            ),
            array(
                "permission_id" => 81,
                "role_id" => 1,
            ),
            array(
                "permission_id" => 82,
                "role_id" => 1,
            ),
            array(
                "permission_id" => 83,
                "role_id" => 1,
            ),
            array(
                "permission_id" => 84,
                "role_id" => 1,
            ),
            array(
                "permission_id" => 85,
                "role_id" => 1,
            ),
            array(
                "permission_id" => 86,
                "role_id" => 1,
            ),
            array(
                "permission_id" => 87,
                "role_id" => 1,
            ),
            array(
                "permission_id" => 88,
                "role_id" => 1,
            ),
            array(
                "permission_id" => 89,
                "role_id" => 1,
            ),
            array(
                "permission_id" => 90,
                "role_id" => 1,
            ),
            array(
                "permission_id" => 91,
                "role_id" => 1,
            ),
            array(
                "permission_id" => 92,
                "role_id" => 1,
            ),
        );

        \DB::table('role_has_permissions')->insert($role_has_permissions);
    }
}
